services:
  api_conversion:
    container_name: api_conversion
    build:
      context: ../backend/apiConversion
    volumes:
      - ../backend/apiConversion:/usr/src/app
      - ../backend/data:/usr/src/data
      - ../backend/csv:/usr/src/csv
    ports:
      - "5002:5002"
    networks:
      - it_game_projet

  api_logs:
    container_name: api_logs
    build:
      context: ../backend/apiLogs
      dockerfile: Dockerfile
    env_file:
      - ../backend/apiLogs/environnements/.env
    volumes:
      - ../backend/apiLogs:/usr/src/app
      - ../backend/data:/usr/src/data
    ports:
      - 5001:5001
    networks:
      - it_game_projet
    command: [ "sh", "./install.sh" ]

  api_affichage:
    container_name: api_affichage
    build:
      context: ../backend/apiAffichage
    env_file:
      - ../backend/apiAffichage/environnements/.env
    volumes:
      - ../backend/apiAffichage:/usr/src/app
      - ../backend/csv:/usr/src/csv
    ports:
      - 5000:5000
    networks:
      - it_game_projet
    command: [ "sh", "./install.sh" ]

  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4200:4200
    volumes:
      - ../frontend:/usr/src/app
    networks:
      - it_game_projet

  nginx:
    container_name: nginx-container
    image: nginx:latest
    ports:
      - "3000:3000"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - it_game_projet
    depends_on:
      - api_logs
      - api_affichage

networks:
  it_game_projet:
    driver: bridge
    external: true
