services:
  apiAffichage:
    container_name: apiAffichage
    build:
      context: ../backend/apiAffichage
    env_file:
      - ../backend/apiAffichage/environnements/.env
    volumes:
      - ../backend/apiAffichage:/usr/src/app
    ports:
      - 5000:5000
    networks:
      - it_game_projet
    command: [ "sh", "./install.sh" ]

  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4200:4200
    volumes:
      - ../frontend:/usr/src/app  
    networks:
      - it_game_projet

networks:
  it_game_projet:
    driver: bridge
    external: true